name: On Development PR or Merge

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "Running tests..."

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '22' 

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint
